-- AlterTable
ALTER TABLE `OrderData` ADD COLUMN `email` VARCHAR(255) NULL,
    ADD COLUMN `status` ENUM('NEW', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'COMPLETED', 'CANCELED', 'RETURNED', 'NOT_DELIVERED') NOT NULL DEFAULT 'NEW';
